#ifndef INPUTMESSAGE_GUARD
#define INPUTMESSAGE_GUARD
#include "util/messenger.h"
//this is an interface for getting detailed information from the messages
//generated by the input system

//messages of type: key_down, key_still_down, key_up
Derive_message_CRTP(message_key){
	public:
	string key;	//key name (a,b,shift,ctrl...)
	message_key();
};

//messages of type: lmb_down, lmb_up, rmb_down, rmb_up
Derive_message_CRTP(message_mouse){
	public:
	vec2i newPos;	//where the mouse is currently
	message_mouse();
};

//messages of type: mouse_move
Derive_message_CRTP(message_mouse_move){
	public:
	vec2i newPos;
	vec2i deltaPos;	//how much the mouse moved since last message
	message_mouse_move();
};

//messages of type: mouse_wheel
Derive_message_CRTP(message_mouse_wheel){
	public:
	vec2i newPos;
	int deltaWheel;	//how much was the wheel moved since last time
	message_mouse_wheel();
};

#endif