#ifndef GAME_GUARD
#define GAME_GUARD
#include "simplemath.h"
#include "resource.h"
#include "paint.h"
#include "GUI.h"
#include "main.h"
#include "render.h"
#include "renderLayer.h"
#include "editmodel.h"
#include "keybinds.h"
#include "util.h"
#include "window.h"
#include "input.h"
#include "renderLow.h"
#include "fontLoader.h"
#include "resource.h"
#include "commands.h"
#include "console.h"
#include "picker.h"
#include "GUIwindows.h"
#ifndef NO_SDL
#include <SDL2/SDL.h>
#endif
#include "camera.h"
#include "editor2.h"
#include "mouse.h"
#include "timer.h"
#endif
