#ifndef GAME_GUARD
#define GAME_GUARD

#include "resource.h"
#include "paint.h"
#include "GUI.h"
#include "main.h"
#include "render.h"
#include "renderLayer.h"
#include "modelprimitives.h"
#include "editmodel.h"
#include "entity.h"
#include "physbox.h"
#include "keybinds.h"
#include "util.h"
#include "window.h"
#include "input.h"
#include "renderLow.h"
#include "fontLoader.h"
#include "resource.h"
#include "octree.h"
#include "commands.h"
#include "console.h"
#include "frameprinter.h"
#include "picker.h"
#include "GUIwindows.h"
#include "ecs.h"
#include "SDL2/SDL.h"
#include "camera.h"
#include "characterController.h"
#include "inputController.h"
#include "AIcontroller.h"
#include "editor2.h"
#include "node_graph.h"

#endif
